import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const data = [
  { name: "Princeton University", studentLifeSnippet: "Princeton's social life revolves heavily around the historic 'Eating Clubs,' blending extreme academic rigor with deeply entrenched Ivy League traditions.", athleticsSnippet: "Athletics take a back seat to academics, though Ivy League rivalries—especially in lacrosse and basketball—draw spirited student support.", safetySnippet: "Princeton is an idyllic, highly affluent, and exceptionally safe suburban town." },
  { name: "Massachusetts Institute of Technology", studentLifeSnippet: "MIT fosters a famously intense, geeky, and collaborative 'hacking' culture where students pull all-nighters solving problem sets and building incredible tech.", athleticsSnippet: "Varsity sports are secondary, but intramurals, 'pirate certificates,' and e-sports are incredibly popular among the student body.", safetySnippet: "Cambridge is a bustling, safe innovation hub, with MIT maintaining excellent campus security." },
  { name: "Harvard University", studentLifeSnippet: "Harvard combines unmatched academic prestige with a residential House system that fosters close-knit communities, secret societies, and intense ambition.", athleticsSnippet: "The Harvard-Yale football game ('The Game') is the premier athletic and social event of the year, steeped in centuries of rivalry.", safetySnippet: "The historic Cambridge campus is incredibly safe, though standard urban awareness applies when venturing into Boston." },
  { name: "Stanford University", studentLifeSnippet: "Stanford ('The Farm') boasts a laid-back, sun-drenched, and deeply entrepreneurial culture where start-up dreams and world-class research collide.", athleticsSnippet: "Stanford is a historic powerhouse in college sports, dominating the Director's Cup with elite programs across all Olympic sports.", safetySnippet: "Palo Alto is an incredibly wealthy, peaceful, and heavily secured area in Silicon Valley." },
  { name: "Yale University", studentLifeSnippet: "Yale's culture is defined by its stunning gothic architecture, intense intellectualism, residential colleges, and legendary secret societies.", athleticsSnippet: "Athletics are highlighted by the historic rivalry with Harvard, particularly the annual massive tailgating events surrounding 'The Game.'", safetySnippet: "New Haven has historical urban challenges, but the Yale campus itself is heavily patrolled and highly secure." },
  { name: "California Institute of Technology", studentLifeSnippet: "Caltech is a tiny, hyper-focused institution where brilliant STEM students bond over grueling problem sets and legendary, elaborate pranks.", athleticsSnippet: "Varsity sports are essentially an afterthought; students are far more focused on research and the inter-house competitions.", safetySnippet: "Pasadena is an affluent, peaceful, and exceptionally safe suburb of Los Angeles." },
  { name: "Duke University", studentLifeSnippet: "Duke offers a 'work hard, play hard' environment featuring gothic architecture, a massive Greek system, and intense Southern pride.", athleticsSnippet: "Blue Devils basketball is an absolute religion; 'Cameron Crazies' camp out for weeks in 'Krzyzewskiville' for the UNC rivalry game.", safetySnippet: "Durham is a revitalized, dynamic city, and the enclosed Duke campus is heavily patrolled and secure." },
  { name: "Johns Hopkins University", studentLifeSnippet: "JHU is famously intense and pre-med focused, fostering a collaborative but grueling academic culture centered around world-class research.", athleticsSnippet: "Hopkins lacrosse is the absolute pride of the university, operating as a Division I powerhouse in an otherwise Division III school.", safetySnippet: "The Homewood campus is a beautiful, secure bubble, though surrounding Baltimore neighborhoods require high urban street smarts." },
  { name: "University of Pennsylvania", studentLifeSnippet: "Penn is known as the 'Social Ivy,' blending elite pre-professional focus (especially Wharton) with a massive, vibrant Greek life scene.", athleticsSnippet: "The historic Penn Relays and Ivy League basketball at the Palestra highlight the athletic calendar.", safetySnippet: "University City is a highly secure, well-lit, and heavily patrolled enclave in West Philadelphia." },
  { name: "Northwestern University", studentLifeSnippet: "Northwestern perfectly balances elite academics with Big Ten sports and a vibrant theater/journalism culture on the shores of Lake Michigan.", athleticsSnippet: "Wildcats football and basketball draw passionate crowds, providing a massive state-school sports feel to an elite private university.", safetySnippet: "Evanston is an affluent, gorgeous, and incredibly safe suburb just north of Chicago." },
  { name: "University of Chicago", studentLifeSnippet: "UChicago is famous for its hyper-intellectual, quirky, and rigorous culture where 'fun comes to die' (ironically), fueled by intense philosophical debates.", athleticsSnippet: "Division III sports are low-profile; the Scavenger Hunt ('Scav') is treated with far more competitive intensity.", safetySnippet: "The Hyde Park neighborhood is heavily patrolled by one of the largest private police forces in the world." },
  { name: "Brown University", studentLifeSnippet: "Brown's Open Curriculum fosters a highly independent, deeply progressive, and laid-back student body focused on exploration and activism.", athleticsSnippet: "Athletics are very low-key, with students far more likely to participate in club sports, arts, or local community organizing.", safetySnippet: "College Hill in Providence is a historic, affluent, and incredibly safe neighborhood." },
  { name: "Cornell University", studentLifeSnippet: "Cornell is a massive, incredibly rigorous Ivy League institution famous for its stunning gorges, intense workload, and legendary hotel school.", athleticsSnippet: "Big Red ice hockey is the biggest athletic draw, featuring passionate traditions like throwing fish onto the ice against Harvard.", safetySnippet: "Ithaca is a picturesque, isolated college town that is exceptionally safe." },
  { name: "Rice University", studentLifeSnippet: "Rice features a tight-knit residential college system that breeds intense quirky traditions, deep loyalty, and highly collaborative STEM students.", athleticsSnippet: "Owls baseball is the historical pride of the athletics department, though the campus vibe is highly academic.", safetySnippet: "The gorgeous, tree-lined campus is located in an affluent, highly secure neighborhood of Houston." },
  { name: "Dartmouth College", studentLifeSnippet: "Dartmouth is deeply defined by its isolated location, massive outdoor recreation culture, and an overwhelmingly dominant Greek system.", athleticsSnippet: "Ivy League sports are popular, but the Winter Carnival and massive outdoor hiking trips are the true cultural centerpieces.", safetySnippet: "Hanover is a tiny, wealthy, and incredibly safe New England town." },
  { name: "Vanderbilt University", studentLifeSnippet: "Vanderbilt ('Vandy') offers a classic Southern 'work hard, play hard' experience, blending elite academics with vibrant Greek life in Nashville.", athleticsSnippet: "Competing in the SEC, Commodores baseball and basketball are major social events, even if football struggles against conference giants.", safetySnippet: "The campus is a stunning, heavily secured arboretum located near the safe, affluent West End of Nashville." },
  { name: "University of Notre Dame", studentLifeSnippet: "Notre Dame is deeply rooted in its Catholic heritage, fostering a massive sense of community, tradition, and residential dorm loyalty.", athleticsSnippet: "Fighting Irish football is an absolute global phenomenon; game days dictate the entire culture and rhythm of the university.", safetySnippet: "The enclosed campus operates almost as its own town and is exceptionally safe and peaceful." },
  { name: "Columbia University in the City of New York", studentLifeSnippet: "Columbia offers a grueling, Core Curriculum-driven Ivy League education fully immersed in the intense, fast-paced lifestyle of Manhattan.", athleticsSnippet: "Athletics take a back seat to the city itself; students are far more engaged in Broadway, Wall Street internships, and NYC nightlife.", safetySnippet: "Morningside Heights is heavily patrolled and generally safe, though standard New York City street smarts are required." },
  { name: "Washington University in St Louis", studentLifeSnippet: "WashU features a collaborative, highly pre-med focused student body that enjoys incredible dorms, top-tier food, and a Midwestern friendliness.", athleticsSnippet: "Division III sports are popular among the athletes, but the wider student body focuses more on intramurals and local St. Louis events.", safetySnippet: "The campus is nestled next to the beautiful Forest Park and affluent suburbs, making it very safe." },
  { name: "University of California-Los Angeles", studentLifeSnippet: "UCLA is massive, diverse, and deeply vibrant, blending elite academics with stunning Southern California weather and a booming social scene.", athleticsSnippet: "Bruins sports are legendary across the board; basketball and football games at the Rose Bowl are massive student traditions.", safetySnippet: "Westwood is one of the most affluent and safe neighborhoods in Los Angeles." },
  { name: "University of California-Berkeley", studentLifeSnippet: "Berkeley (Cal) is world-renowned for its intense academic rigor, deeply rooted history of political activism, and highly progressive student body.", athleticsSnippet: "Cal football and the massive 'Big Game' rivalry with Stanford are central pillars of the university's spirited sports culture.", safetySnippet: "The surrounding city of Berkeley requires high urban awareness, though the campus core is well-patrolled." },
  { name: "University of Michigan-Ann Arbor", studentLifeSnippet: "UMich offers the ultimate, massive 'work hard, play hard' state-school experience, defined by intense academics and an incredibly spirited student body.", athleticsSnippet: "Wolverines football at 'The Big House' (the largest stadium in the US) is a colossal, defining cultural event for the university.", safetySnippet: "Ann Arbor is repeatedly ranked as one of the best and safest college towns in America." },
  { name: "Louisiana State University and Agricultural & Mechanical College", studentLifeSnippet: "LSU is a colossal, spirited powerhouse defined by a massive Greek system, incredible Cajun food culture, and intense state pride.", athleticsSnippet: "Saturday nights in 'Death Valley' for SEC football are legendary, creating one of the most intimidating and loud sports atmospheres in the world.", safetySnippet: "Baton Rouge requires some urban awareness, but the massive campus is well-policed." },
  { name: "New Mexico State University-Dona Ana", studentLifeSnippet: "As a community college branch of NMSU, Dona Ana offers a highly supportive, commuter-focused environment geared toward technical skills and local careers.", athleticsSnippet: "Students generally support the major Division I sports teams of the main NMSU campus nearby.", safetySnippet: "Las Cruces is a quiet, spread-out city that is generally very safe for students." },
  { name: "Kent State University at Ashtabula", studentLifeSnippet: "This regional campus provides a quiet, highly personalized, and commuter-heavy education right on the shores of Lake Erie.", athleticsSnippet: "Athletics are practically non-existent on this branch campus, with students focused entirely on academics and local jobs.", safetySnippet: "Ashtabula is a quiet, working-class coastal town that is generally very safe." },
  { name: "North Dakota State University-Main Campus", studentLifeSnippet: "NDSU is a deeply agricultural and engineering-driven powerhouse with a famously resilient, friendly, and fiercely loyal student body.", athleticsSnippet: "Bison football is an FCS dynasty, and game days at the Fargodome are massive, statewide spectacles.", safetySnippet: "Fargo is a large but incredibly safe Midwestern city with a very secure campus." },
  { name: "Boise State University", studentLifeSnippet: "Boise State features a highly outdoorsy, rapidly growing, and deeply spirited student body integrated closely with the booming tech hub of Boise.", athleticsSnippet: "Broncos football, famous for its iconic 'Smurf Turf' (blue field), absolutely dominates the athletic and social calendar.", safetySnippet: "Boise is widely recognized as one of the cleanest, friendliest, and safest cities in the West." },
  { name: "Portland State University", studentLifeSnippet: "PSU is a gritty, incredibly diverse, and heavily commuter-focused urban campus deeply integrated into downtown Portland.", athleticsSnippet: "Vikings sports play a minor role; students are far more engaged in Portland's quirky food, music, and activist scenes.", safetySnippet: "The downtown campus requires high urban street smarts due to city-wide homelessness and property crime issues." },
  { name: "University of Toledo", studentLifeSnippet: "UToledo is a massive, practical, and highly commuter-friendly research institution with strong ties to local Ohio industries.", athleticsSnippet: "Rockets football in the MAC draws solid local support and serves as the primary athletic event of the fall.", safetySnippet: "The campus is relatively safe, though surrounding Toledo neighborhoods require standard urban awareness." },
  { name: "University of Missouri-Kansas City", studentLifeSnippet: "UMKC offers a deeply urban, commuter-heavy campus culture with a strong focus on health sciences, business, and local Kansas City internships.", athleticsSnippet: "Roos basketball is the main athletic focus, though the overall sports culture is relatively low-key.", safetySnippet: "Located in the busy Country Club Plaza area, the campus is vibrant but requires typical city street smarts." },
  { name: "University of New Mexico-Gallup Campus", studentLifeSnippet: "UNM Gallup is a vital, tight-knit regional campus serving a highly diverse student body, particularly Native American communities, with a focus on technical education.", athleticsSnippet: "Athletics are very minor, as the campus focuses heavily on adult education, trades, and local community building.", safetySnippet: "Gallup is a rugged, historic town where the campus serves as a quiet, safe educational hub." },
  { name: "Cleveland State University", studentLifeSnippet: "CSU is an energetic, heavily commuter-focused urban campus that utilizes downtown Cleveland as a massive living laboratory for its students.", athleticsSnippet: "Vikings basketball is the primary athletic draw, but students are often more focused on local jobs and city life.", safetySnippet: "The downtown campus is heavily patrolled by university police, though standard city precautions apply." },
  { name: "University of North Texas", studentLifeSnippet: "UNT is famous for its incredibly robust music and arts scene, fostering a laid-back, highly creative, and diverse student body in Denton.", athleticsSnippet: "Mean Green football and basketball are growing in popularity, but the incredible local music festivals often steal the spotlight.", safetySnippet: "Denton is a beloved, quirky, and generally very safe college town." },
  { name: "California State University-Fullerton", studentLifeSnippet: "CSUF is a colossal, incredibly diverse commuter school deeply tied to Southern California's business and entertainment industries.", athleticsSnippet: "Titans baseball is a historic national powerhouse, serving as the absolute pride of the university's athletic department.", safetySnippet: "Fullerton is a safe, busy suburban city with excellent campus security measures." },
  { name: "University of Wisconsin-Milwaukee", studentLifeSnippet: "UWM offers a gritty, diverse, and vibrant urban campus experience located just blocks from the shores of Lake Michigan.", athleticsSnippet: "Panthers basketball is the primary sport, as the school lacks a football team, but city nightlife often takes precedence.", safetySnippet: "The campus is situated in a busy residential area of Milwaukee requiring standard urban awareness." },
  { name: "Wright State University-Main Campus", studentLifeSnippet: "Wright State is a heavily commuter-based, highly accessible campus famous for its extensive underground tunnel system to avoid the Ohio cold.", athleticsSnippet: "Raiders basketball is the major athletic draw, uniting the predominantly commuter student body.", safetySnippet: "Fairborn is a quiet, very safe suburb located near a major Air Force base." },
  { name: "Central Michigan University", studentLifeSnippet: "CMU provides a classic, deeply spirited, and friendly Midwestern state-school experience with a massive focus on education and business.", athleticsSnippet: "Chippewas football in the MAC serves as the massive social focal point for the fall semester.", safetySnippet: "Mount Pleasant is a quintessential, quiet college town that prioritizes student safety." },
  { name: "Northern Illinois University", studentLifeSnippet: "NIU is a diverse, hard-working, and affordable state school with a large commuter population drawn from the greater Chicago area.", athleticsSnippet: "Huskies football is historically strong in the MAC and drives the majority of campus school spirit.", safetySnippet: "DeKalb is a typical, safe Midwestern college town with a strong campus police presence." },
  { name: "University of Alaska Fairbanks", studentLifeSnippet: "UAF is uniquely rugged and intensely outdoorsy, featuring a student body that embraces extreme weather, the northern lights, and deep Arctic research.", athleticsSnippet: "Nanooks ice hockey and rifle teams dominate the incredibly unique athletic culture here.", safetySnippet: "Fairbanks is a tough, remote city, but the campus is deeply community-oriented and extremely safe." },
  { name: "Texas Tech University", studentLifeSnippet: "Texas Tech boasts a massive, fiercely loyal, and spirited student body isolated in the high plains of West Texas.", athleticsSnippet: "Red Raiders football and the iconic tradition of throwing tortillas on the field highlight an incredibly loud and passionate sports culture.", safetySnippet: "Lubbock is a massive, sprawling college town deeply protective of its student population." },
  { name: "University of Nevada-Reno", studentLifeSnippet: "UNR offers a classic, beautiful brick campus with a highly spirited, outdoorsy student body that takes full advantage of nearby Lake Tahoe.", athleticsSnippet: "Wolf Pack football and basketball are massive cultural events that deeply unite the city of Reno.", safetySnippet: "The campus is situated on a hill overlooking downtown and is heavily secured and safe." },
  { name: "University of Hawaii at Manoa", studentLifeSnippet: "UH Manoa features a breathtaking, highly diverse, and deeply laid-back campus culture completely immersed in the incredible island lifestyle.", athleticsSnippet: "Rainbow Warriors volleyball and football are huge sources of state-wide pride.", safetySnippet: "Honolulu is generally safe, though standard city awareness is needed; the campus itself is heavily guarded." },
  { name: "University of North Carolina Wilmington", studentLifeSnippet: "UNCW offers a gorgeous, sun-soaked coastal campus where the incredibly laid-back student body frequently balances academics with surfing.", athleticsSnippet: "Seahawks basketball is the premier sport, but the athletic culture is mostly defined by beach and water sports.", safetySnippet: "Wilmington is a safe, beautiful coastal city with a highly secure campus." },
  { name: "Pace University", studentLifeSnippet: "Pace utilizes the financial district of Manhattan as its campus, fostering a hyper-driven, pre-professional student body focused on Wall Street internships.", athleticsSnippet: "Athletics are practically non-existent; the hustle of New York City is the primary extracurricular activity.", safetySnippet: "Lower Manhattan is heavily policed and generally safe, though it requires constant urban awareness." },
  { name: "University of Colorado Denver/Anschutz Medical Campus", studentLifeSnippet: "This campus is heavily graduate and medically focused, creating a serious, intensely rigorous, and highly professional urban community.", athleticsSnippet: "Students focus entirely on clinical rotations and research; there is no traditional college sports culture here.", safetySnippet: "The Anschutz campus is a highly secure, massive medical complex in the Denver metro area." },
  { name: "Bentley University", studentLifeSnippet: "Bentley is a premier, highly pre-professional business university where students are intensely focused on finance, networking, and corporate careers.", athleticsSnippet: "Falcons Division II basketball and ice hockey enjoy solid support from the incredibly tight-knit student body.", safetySnippet: "Waltham is an affluent, heavily secured suburb of Boston, making the campus exceptionally safe." },
  { name: "Georgia State University", studentLifeSnippet: "GSU is a massive, incredibly diverse, and rapidly growing urban university completely integrated into downtown Atlanta.", athleticsSnippet: "Panthers basketball and the relatively new football program are steadily building a strong urban sports culture.", safetySnippet: "The downtown Atlanta campus requires high urban street smarts, though GSU operates a massive police force." },
  { name: "Ohio University-Eastern Campus", studentLifeSnippet: "This tiny regional campus offers a highly personalized, deeply rural, and heavily commuter-focused education in the Appalachian foothills.", athleticsSnippet: "Athletics are minor, with students focusing heavily on local jobs and transitioning to the main campus.", safetySnippet: "The rural setting in St. Clairsville is extremely quiet, peaceful, and safe." },
  { name: "University of Missouri-St Louis", studentLifeSnippet: "UMSL is a hardworking, diverse, and heavily commuter-driven campus providing affordable education to the greater St. Louis area.", athleticsSnippet: "Tritons Division II sports have a local following, but the culture is overwhelmingly focused on academics and careers.", safetySnippet: "The suburban campus is heavily patrolled and safe, though it borders some rougher areas of St. Louis." },
  { name: "San Francisco State University", studentLifeSnippet: "SF State boasts a highly diverse, politically active, and incredibly progressive student body deeply engaged with the culture of San Francisco.", athleticsSnippet: "Gators athletics are low-profile; students are far more focused on arts, local activism, and city life.", safetySnippet: "The campus in the foggy Lake Merced neighborhood is quiet and generally very safe." }
];

async function main() {
  let count = 0;
  for (const college of data) {
    try {
      const result = await prisma.college.updateMany({
        where: { name: college.name },
        data: {
          studentLifeSnippet: college.studentLifeSnippet,
          athleticsSnippet: college.athleticsSnippet,
          safetySnippet: college.safetySnippet
        }
      });
      if (result.count > 0) count++;
      console.log(`Updated ${college.name}`);
    } catch (e) {
      console.error(`Failed to update ${college.name}`, e);
    }
  }
  console.log(`Successfully batch updated ${count} colleges.`);
}

main().finally(() => prisma.$disconnect());
