import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const data = [
  { name: "Rensselaer Polytechnic Institute", studentLifeSnippet: "RPI fosters a deeply nerdy, highly collaborative, and intensely rigorous engineering-focused culture.", athleticsSnippet: "Division III sports play a minor role, though the Division I men's ice hockey team enjoys massive student support.", safetySnippet: "The Troy campus is secure, but typical urban street smarts are recommended when heading downtown." },
  { name: "Pepperdine University", studentLifeSnippet: "With breathtaking views of the Pacific, Pepperdine's culture is rooted in strong Christian values, dry-campus rules, and laid-back beach life.", athleticsSnippet: "Intramurals and outdoor recreation dominate, though the Division I Waves find success in water polo and tennis.", safetySnippet: "Located in affluent Malibu, the campus is enclosed and considered incredibly safe." },
  { name: "Santa Clara University", studentLifeSnippet: "SCU blends Jesuit traditions with a highly entrepreneurial, Silicon Valley-driven, and socially vibrant campus lifestyle.", athleticsSnippet: "While lacking a football team, Division I basketball and soccer games are popular campus events.", safetySnippet: "Situated in the heart of Silicon Valley, the campus is heavily patrolled and exceptionally secure." },
  { name: "University of Miami", studentLifeSnippet: "UM offers a flashy, diverse, and vibrant lifestyle heavily influenced by Miami's international culture and strong Greek life.", athleticsSnippet: "The Hurricanes football program is legendary, with game days acting as massive, city-wide social events.", safetySnippet: "The Coral Gables area is an affluent, safe suburb, though standard precautions apply when exploring greater Miami." },
  { name: "Northeastern University Oakland", studentLifeSnippet: "This Mills College campus offers an intimate, highly progressive, and close-knit environment integrated into Northeastern's global network.", athleticsSnippet: "Athletics are low-key, with most students focusing on local outdoor activities or traveling to the Boston campus for major sports.", safetySnippet: "The campus is a quiet oasis in Oakland with strong perimeter security." },
  { name: "Tulane University of Louisiana", studentLifeSnippet: "Tulane students embrace a legendary 'work hard, play hard' lifestyle deeply integrated into the cultural heartbeat of New Orleans.", athleticsSnippet: "While Division I football and baseball have dedicated fans, the primary 'sport' is often the massive Mardi Gras social season.", safetySnippet: "Uptown New Orleans requires strict urban awareness, though Tulane heavily polices its immediate perimeter." },
  { name: "University of Maryland-College Park", studentLifeSnippet: "UMD is a massive, diverse state school with a bustling, spirited campus culture and close proximity to Washington D.C.", athleticsSnippet: "Big Ten athletics are a huge draw, with deeply passionate 'Terp' fans making basketball games especially rowdy.", safetySnippet: "College Park is a busy college town; the campus itself is heavily secured with numerous safety programs." },
  { name: "Virginia Polytechnic Institute and State University", studentLifeSnippet: "Virginia Tech is renowned for its incredibly tight-knit 'Hokie Nation' community, legendary dining hall food, and collaborative engineering focus.", athleticsSnippet: "Hokie football is an absolute religion in Blacksburg, famous for the electric 'Enter Sandman' entrance.", safetySnippet: "Blacksburg is routinely ranked as one of the safest and most picturesque college towns in America." },
  { name: "Syracuse University", studentLifeSnippet: "Syracuse balances rigorous academics (especially in communications) with a massive, spirited Greek life presence and cold winters.", athleticsSnippet: "Orange basketball in the Carrier Dome is the focal point of school pride, drawing massive student crowds.", safetySnippet: "The campus is relatively safe, but students are advised to use the university shuttle system at night." },
  { name: "University of Connecticut", studentLifeSnippet: "UConn is a massive, isolated state school where campus life revolves heavily around Greek organizations and immense school spirit.", athleticsSnippet: "UConn is widely considered the 'Basketball Capital of the World,' with the men's and women's teams dominating the social calendar.", safetySnippet: "The rural Storrs campus is effectively its own town and is considered extremely safe." },
  { name: "University of Pittsburgh-Pittsburgh Campus", studentLifeSnippet: "Pitt offers an urban, fast-paced environment integrated directly into the city, known for strong health sciences and fierce school pride.", athleticsSnippet: "Pitt football games at Acrisure Stadium and the 'Sweet Caroline' tradition are central to the student experience.", safetySnippet: "The Oakland neighborhood is highly active and well-policed by both Pitt and local authorities." },
  { name: "Southern Methodist University", studentLifeSnippet: "SMU is famous for its wealthy, preppy, and highly social student body, anchored by a beautiful campus and robust Greek life in Dallas.", athleticsSnippet: "Tailgating on 'The Boulevard' before Mustangs football games is the premier social tradition of the fall semester.", safetySnippet: "The University Park enclave is exceptionally affluent, secure, and heavily policed." },
  { name: "George Washington University", studentLifeSnippet: "GW lacks a traditional campus, fully immersing its highly politically-active, internship-driven student body into the heart of D.C.", athleticsSnippet: "Athletics take a back seat to politics and professional networking, though basketball games are popular.", safetySnippet: "Located in Foggy Bottom near the White House, the area is heavily monitored by multiple federal and local agencies." },
  { name: "Clemson University", studentLifeSnippet: "Clemson boasts a famously friendly, deeply loyal, and deeply Southern campus culture with massive school spirit.", athleticsSnippet: "Clemson football is a national powerhouse, and game days in 'Death Valley' define the student experience.", safetySnippet: "The college town of Clemson is small, tightly knit, and widely considered extremely safe." },
  { name: "Worcester Polytechnic Institute", studentLifeSnippet: "WPI features a unique project-based curriculum that fosters a highly collaborative, nerdy, and intense engineering culture.", athleticsSnippet: "Varsity athletics are secondary to academics, but intramural sports are highly popular stress relievers.", safetySnippet: "The campus is a secure enclave in Worcester, with robust university police patrols." },
  { name: "University of Minnesota-Duluth", studentLifeSnippet: "UMD students are notably outdoorsy, resilient to extreme cold, and heavily engaged in winter sports and nature.", athleticsSnippet: "Division I men's and women's ice hockey absolutely dominate the athletic culture here.", safetySnippet: "Duluth is a very safe, friendly Midwestern city with a highly secure campus." },
  { name: "North Carolina State University at Raleigh", studentLifeSnippet: "NC State offers a massive, STEM-driven, down-to-earth culture deeply rooted in agricultural and engineering traditions.", athleticsSnippet: "The 'Wolfpack' boasts fierce school pride, with intense rivalries driving the massive football and basketball tailgating scenes.", safetySnippet: "Raleigh is a safe, bustling tech hub, and the campus is well-patrolled." },
  { name: "Brigham Young University", studentLifeSnippet: "BYU has a uniquely conservative, sober, and deeply religious campus culture strictly governed by the LDS Church's Honor Code.", athleticsSnippet: "BYU athletics enjoy massive, passionate support from both students and a global religious alumni network.", safetySnippet: "Provo is consistently ranked as one of the absolute safest cities in the United States." },
  { name: "Stevens Institute of Technology", studentLifeSnippet: "Stevens is a small, intense engineering school featuring incredible views of the NYC skyline and a highly career-focused student body.", athleticsSnippet: "Division III athletics exist, but academics and proximity to NYC internships dominate the culture.", safetySnippet: "Hoboken is a highly affluent, bustling, and very safe urban suburb." },
  { name: "University of California-Santa Cruz", studentLifeSnippet: "UCSC is famous for its gorgeous redwood forest campus, highly progressive student body, and deeply laid-back, counter-cultural vibe.", athleticsSnippet: "There is no football team; instead, surfing, hiking, and the quirky 'Banana Slug' mascot define the athletic culture.", safetySnippet: "The isolated, forest-enclosed campus is exceptionally safe and peaceful." },
  { name: "University of Iowa", studentLifeSnippet: "Iowa is the quintessential Big Ten university, known for an incredibly social student body and top-tier writing programs.", athleticsSnippet: "Hawkeye football is a massive tradition, highlighted by the heartwarming 'Hawkeye Wave' to the adjacent children's hospital.", safetySnippet: "Iowa City is a classic, deeply literary college town that is very safe." },
  { name: "Michigan State University", studentLifeSnippet: "MSU is a colossal, spirited institution with a beautiful, sprawling campus, massive Greek life, and strong agricultural roots.", athleticsSnippet: "Spartan football and basketball are central to campus life, fostering intense statewide rivalries.", safetySnippet: "East Lansing is a dedicated college town with strong community policing and a generally safe environment." },
  { name: "University of Delaware", studentLifeSnippet: "UD offers a classic, picturesque East Coast campus experience heavily driven by Greek life and an outgoing student body.", athleticsSnippet: "Blue Hens football and basketball draw solid crowds, and the tailgating scene is very robust.", safetySnippet: "Newark is a quaint, bustling college town heavily centered around student safety." },
  { name: "American University", studentLifeSnippet: "AU students are famously wonky, hyper-focused on international relations, and deeply engaged in political activism.", athleticsSnippet: "Athletics are a minor component of the AU experience; internships on Capitol Hill are the real sport.", safetySnippet: "Located in the affluent Tenleytown neighborhood, the campus is extremely safe." },
  { name: "Baylor University", studentLifeSnippet: "Baylor blends strong Southern Baptist traditions with massive state-school energy and an incredibly loyal, spirited student body.", athleticsSnippet: "Baylor football and basketball are national powerhouses, driving massive weekend social events.", safetySnippet: "Waco is generally safe, and the campus maintains a strict, highly secure perimeter." },
  { name: "Fordham University", studentLifeSnippet: "Fordham offers a classic, gothic campus oasis in the Bronx, deeply rooted in Jesuit values and proximity to Manhattan.", athleticsSnippet: "Athletics play a minor role, though the 'Battle of the Bronx' basketball games are highly spirited.", safetySnippet: "The Rose Hill campus is heavily gated and very secure, though students must be street-smart in the surrounding Bronx." },
  { name: "Yeshiva University", studentLifeSnippet: "Yeshiva offers a unique dual curriculum combining intensive Jewish studies with rigorous secular academics in a deeply orthodox environment.", athleticsSnippet: "Maccabees basketball is the pride of the school, uniquely bringing the tight-knit community together.", safetySnippet: "Located in Washington Heights, the campus is generally safe and heavily guarded." },
  { name: "University of Colorado Boulder", studentLifeSnippet: "CU Boulder is renowned for its breathtaking mountain views, highly active outdoorsy culture, and laid-back, progressive student body.", athleticsSnippet: "Buffaloes football at Folsom Field is legendary, often followed by weekend ski trips or hiking.", safetySnippet: "Boulder is an affluent, highly secure town with minimal crime." },
  { name: "Oregon State University", studentLifeSnippet: "OSU is a major research hub with a friendly, down-to-earth student body deeply engaged in forestry and engineering.", athleticsSnippet: "Beavers baseball and football are massive cultural pillars, drawing incredibly loyal local crowds.", safetySnippet: "Corvallis is a quintessential, peaceful Pacific Northwest college town." },
  { name: "Indiana University-Bloomington", studentLifeSnippet: "IU is visually stunning and socially vibrant, known for its massive Greek system and the legendary Little 500 bicycle race.", athleticsSnippet: "Hoosiers basketball is an absolute religion here, deeply ingrained in the state's cultural identity.", safetySnippet: "Bloomington is a classic, welcoming college town that prioritizes student safety." },
  { name: "Marquette University", studentLifeSnippet: "Marquette blends Jesuit service-oriented values with a gritty, urban Milwaukee lifestyle and a tight-knit community.", athleticsSnippet: "Golden Eagles basketball is the heartbeat of the campus, as the school lacks a football team.", safetySnippet: "The urban campus requires street smarts, but the university employs extensive safety patrols." },
  { name: "Temple University", studentLifeSnippet: "Temple is a massive, gritty, and incredibly diverse commuter-heavy institution integrated deeply into North Philadelphia.", athleticsSnippet: "Owls basketball and football have passionate local followings, reflecting the city's tough sports culture.", safetySnippet: "North Philly requires high urban awareness, but Temple maintains one of the largest campus police forces in the nation." },
  { name: "University of San Francisco", studentLifeSnippet: "USC offers a socially conscious, diverse, and progressive Jesuit education right in the geographic center of San Francisco.", athleticsSnippet: "Athletics are low-profile, with students far more engaged in city exploration and social justice clubs.", safetySnippet: "The hilltop campus is located in a quiet, very safe residential neighborhood." },
  { name: "Howard University", studentLifeSnippet: "As 'The Mecca,' Howard is a deeply historic, culturally vibrant HBCU renowned for producing elite Black leaders and a massive homecoming celebration.", athleticsSnippet: "Bison sports, particularly football and the accompanying marching band culture, are legendary.", safetySnippet: "The D.C. campus requires typical urban street smarts, but the community is highly protective." },
  { name: "University of South Carolina-Columbia", studentLifeSnippet: "South Carolina offers a massive, deeply Southern state-school vibe with an immense Greek system and spirited social scene.", athleticsSnippet: "Gamecocks football and women's basketball are cultural juggernauts that define the student experience.", safetySnippet: "Columbia is a busy capital city with typical urban issues, but the campus core is well-secured." },
  { name: "Auburn University", studentLifeSnippet: "Auburn is famous for its 'Auburn Family' culture, boasting an incredibly friendly, loyal, and tradition-rich student body.", athleticsSnippet: "SEC football is everything here, highlighted by the iconic tradition of rolling Toomer's Corner after a victory.", safetySnippet: "Auburn is a highly secure, classic Southern college town." },
  { name: "University of Utah", studentLifeSnippet: "The 'U' offers a massive commuter population mixed with deeply outdoorsy students who take full advantage of the nearby Wasatch Mountains.", athleticsSnippet: "Utes football and gymnastics are massive draws, fostering intense state-wide rivalries.", safetySnippet: "Salt Lake City is widely considered a very safe, clean, and well-policed urban area." },
  { name: "University of Arizona", studentLifeSnippet: "Arizona features a massive, sun-soaked campus with an incredibly vibrant, highly social, and active Greek life scene.", athleticsSnippet: "Wildcats basketball is a national powerhouse and the absolute center of campus sports pride.", safetySnippet: "Tucson requires some urban awareness off-campus, but the university grounds are heavily monitored." },
  { name: "University of Massachusetts-Amherst", studentLifeSnippet: "UMass is a colossal institution famous for its legendary dining hall food and an incredibly spirited, sometimes rowdy student body.", athleticsSnippet: "Minutemen hockey and basketball drive the athletic culture on this massive New England campus.", safetySnippet: "Amherst is a highly secure, idyllic college town part of the Five College Consortium." },
  { name: "Drexel University", studentLifeSnippet: "Drexel's unique co-op program creates a highly pre-professional, fast-paced, and intense campus culture focused heavily on career readiness.", athleticsSnippet: "Athletics are secondary to the grueling co-op schedules, though intramurals are popular.", safetySnippet: "Sharing the University City area with Penn, the campus is heavily patrolled and safe." },
  { name: "Arizona State University Campus Immersion", studentLifeSnippet: "ASU is a colossal, innovative powerhouse known for its incredibly vibrant, sun-soaked social scene and massive student population.", athleticsSnippet: "Sun Devil football and the 'Curtain of Distraction' at basketball games highlight a massive sports culture.", safetySnippet: "Tempe is a bustling college town that is well-policed, though students must be mindful during massive events." },
  { name: "Saint Louis University", studentLifeSnippet: "SLU is a deeply community-oriented Jesuit university with a diverse student body engaged in rigorous academics and local service.", athleticsSnippet: "Billikens basketball is the primary athletic draw, serving as a major social event in the winter.", safetySnippet: "The Midtown St. Louis campus is heavily gated and secured, though the surrounding city requires street smarts." },
  { name: "Loyola University Chicago", studentLifeSnippet: "Loyola offers a gorgeous, lakeside urban campus with a student body deeply committed to Jesuit values, nursing, and social justice.", athleticsSnippet: "Ramblers basketball skyrocketed in popularity following their Final Four run, defining campus sports.", safetySnippet: "The Rogers Park neighborhood is generally safe, and the campus itself is highly secure." },
  { name: "University of Kentucky", studentLifeSnippet: "UK is a massive, spirited state school characterized by a strong Greek system and deep-rooted Southern/Midwestern traditions.", athleticsSnippet: "Kentucky basketball is a cultural monolith, essentially serving as a religion for the entire state.", safetySnippet: "Lexington is a safe, welcoming city, and the campus operates a robust police force." },
  { name: "The University of Tennessee-Knoxville", studentLifeSnippet: "UT is defined by immense school pride, massive Greek life, and a sea of 'Volunteer Orange' dominating the lively social scene.", athleticsSnippet: "Volunteers football and the unique 'Vol Navy' tailgating on the river are legendary SEC traditions.", safetySnippet: "Knoxville is a safe, friendly college town with excellent campus security measures." },
  { name: "University of Oklahoma-Health Sciences Center", studentLifeSnippet: "This specialized campus is entirely graduate and professionally focused, fostering an intensely rigorous, career-driven medical community.", athleticsSnippet: "Students here generally follow the massive Sooners sports culture of the main Norman campus.", safetySnippet: "Located in the medical district of Oklahoma City, the campus is highly secure and professional." },
  { name: "University of Nebraska-Lincoln", studentLifeSnippet: "UNL features a deeply loyal, friendly Midwestern culture where agriculture, engineering, and massive state pride intersect.", athleticsSnippet: "Cornhuskers football is legendary, with the stadium becoming the third-largest 'city' in the state on game days.", safetySnippet: "Lincoln is widely regarded as an incredibly safe, family-friendly Midwestern capital." },
  { name: "University of South Florida", studentLifeSnippet: "USF is a rapidly rising, massive research university with a diverse, commuter-heavy student body enjoying the sunny Tampa lifestyle.", athleticsSnippet: "Bulls football games at Raymond James Stadium are the highlight of the athletic calendar.", safetySnippet: "The sprawling campus is generally safe, with a highly visible university police department." },
  { name: "University at Buffalo", studentLifeSnippet: "UB is a massive, research-heavy SUNY school where students bond over rigorous academics and enduring intense winter weather.", athleticsSnippet: "Bulls football and basketball have strong local followings, but intramurals are heavily favored by students.", safetySnippet: "The suburban North Campus is incredibly safe and largely isolated from the city of Buffalo." },
  { name: "University of California-Riverside", studentLifeSnippet: "UCR is celebrated for its immense diversity, social mobility, and a highly collaborative, laid-back student body.", athleticsSnippet: "Without a football team, the athletic culture is relatively quiet, with students focusing more on clubs and academics.", safetySnippet: "The campus is considered very safe, with strong community policing efforts in place." },
  { name: "New Jersey Institute of Technology", studentLifeSnippet: "NJIT is an intensely rigorous, heavily commuter-based STEM school where students are hyper-focused on engineering and career outcomes.", athleticsSnippet: "Varsity athletics exist but take a major back seat to academics and technological research.", safetySnippet: "Located in University Heights, Newark, the campus is highly secured, though surrounding areas require urban awareness." },
  { name: "University of Illinois Chicago", studentLifeSnippet: "UIC is a massive, incredibly diverse commuter school deeply integrated into the medical and urban fabric of Chicago.", athleticsSnippet: "Flames basketball is the primary sport, but the culture is largely academic and commuter-driven.", safetySnippet: "The campus is heavily patrolled by UIC police, though students must navigate standard Chicago urban risks." },
  { name: "University of San Diego", studentLifeSnippet: "USD boasts an immaculately beautiful, resort-like campus with a laid-back, affluent student body and strong Catholic heritage.", athleticsSnippet: "Toreros sports are low-key, with students preferring surfing, beach volleyball, and enjoying the San Diego weather.", safetySnippet: "The hilltop campus in Linda Vista is considered exceptionally safe and heavily secured." },
  { name: "George Mason University", studentLifeSnippet: "GMU is a highly diverse, politically active, and rapidly growing institution with a massive commuter population near D.C.", athleticsSnippet: "Patriots basketball is the historical pride of the school, driving the majority of athletic spirit.", safetySnippet: "Fairfax is an affluent, highly secure suburb of Washington D.C." },
  { name: "University of Missouri-Columbia", studentLifeSnippet: "Mizzou offers a classic, massive state school experience with the world's first journalism school and an incredibly spirited Greek culture.", athleticsSnippet: "Tigers football in the SEC is the absolute anchor of the university's massive social and athletic identity.", safetySnippet: "Columbia is a quintessential college town, generally safe, with excellent campus police resources." },
  { name: "The University of Alabama", studentLifeSnippet: "Bama is legendary for its massive, influential Greek system ('Bama Rush') and a deeply ingrained, fiercely loyal Southern campus culture.", athleticsSnippet: "Crimson Tide football is an unstoppable cultural force that completely defines the university's identity.", safetySnippet: "Tuscaloosa is a dedicated college town, heavily policed to protect the massive student population." },
  { name: "University of Kansas", studentLifeSnippet: "KU features a beautiful, hilly campus with a famously friendly Midwestern vibe and a highly social, spirited student body.", athleticsSnippet: "Jayhawks basketball is legendary, with Allen Fieldhouse offering one of the most electric atmospheres in sports.", safetySnippet: "Lawrence is consistently rated as one of the best and safest college towns in the nation." },
  { name: "University of Cincinnati-Main Campus", studentLifeSnippet: "UC is a gritty, innovative urban campus famous for inventing the co-op program, blending intense pre-professional focus with strong city pride.", athleticsSnippet: "Bearcats football and basketball are massive draws, deeply integrating the university with the city of Cincinnati.", safetySnippet: "The campus is an urban environment requiring street smarts, but the university maintains a massive security perimeter." }
];

async function main() {
  let count = 0;
  for (const college of data) {
    try {
      await prisma.college.updateMany({
        where: { name: college.name },
        data: {
          studentLifeSnippet: college.studentLifeSnippet,
          athleticsSnippet: college.athleticsSnippet,
          safetySnippet: college.safetySnippet
        }
      });
      count++;
      console.log(`Updated ${college.name}`);
    } catch (e) {
      console.error(`Failed to update ${college.name}`, e);
    }
  }
  console.log(`Successfully batch updated ${count} colleges.`);
}

main().finally(() => prisma.$disconnect());
