import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const data = [
  { name: "California State University-Sacramento", studentLifeSnippet: "Sac State features a lush, tree-filled campus with a highly diverse, commuter-heavy student body deeply tied to the state capital.", athleticsSnippet: "Hornets football and the massive 'Causeway Classic' rivalry game with UC Davis dictate the fall sports culture.", safetySnippet: "The campus is beautifully nestled along the American River and is generally very safe." },
  { name: "California State University-Northridge", studentLifeSnippet: "CSUN is a massive, incredibly diverse commuter hub deeply integrated into the San Fernando Valley's entertainment and business industries.", athleticsSnippet: "Matadors sports are low-profile; students are far more focused on city life, jobs, and the local arts scene.", safetySnippet: "The campus requires typical Los Angeles urban awareness but is heavily patrolled by university police." },
  { name: "Illinois State University", studentLifeSnippet: "ISU offers a classic, friendly Midwestern state-school vibe with strong roots in education and a highly active student body.", athleticsSnippet: "Redbirds football in the FCS draws solid crowds, fostering a strong sense of local pride.", safetySnippet: "Normal is a quintessential, quiet, and exceptionally safe college town." },
  { name: "Wayne State University", studentLifeSnippet: "Wayne State is a gritty, incredibly diverse urban research university completely immersed in the revitalized heart of Detroit.", athleticsSnippet: "Athletics are secondary to the massive pre-professional and commuter culture, though the campus is proud of its Detroit roots.", safetySnippet: "The Midtown Detroit campus requires urban street smarts, but the immediate university area is heavily policed." },
  { name: "Southern Illinois University-Carbondale", studentLifeSnippet: "SIU features a deeply outdoorsy, relaxed campus culture set against the beautiful Shawnee National Forest in southern Illinois.", athleticsSnippet: "Salukis basketball is the historical pride of the university, serving as a major community event.", safetySnippet: "Carbondale is a rugged, friendly college town where students feel highly secure." },
  { name: "Florida Atlantic University", studentLifeSnippet: "FAU offers a stunning, sun-soaked coastal campus where the highly diverse student body frequently balances academics with beach life.", athleticsSnippet: "Owls football has seen a massive resurgence, building a strong, vibrant tailgating culture.", safetySnippet: "Boca Raton is an affluent, highly secure resort city." },
  { name: "Georgia Southern University", studentLifeSnippet: "Georgia Southern is beloved for its classic, beautiful campus and a deeply friendly, tight-knit Southern student culture.", athleticsSnippet: "Eagles football is absolutely massive here, boasting six national championships and deeply spirited game days.", safetySnippet: "Statesboro is a dedicated, quiet, and very safe college town." },
  { name: "Middle Tennessee State University", studentLifeSnippet: "MTSU is a massive, diverse campus renowned for its elite recording industry programs and proximity to Nashville.", athleticsSnippet: "Blue Raiders football is the major athletic draw, serving as a focal point for campus socialization.", safetySnippet: "Murfreesboro is a rapidly growing but generally safe suburban college town." },
  { name: "Sam Houston State University", studentLifeSnippet: "SHSU provides a gritty, deeply traditional Texas state-school experience with a massive focus on criminal justice and agriculture.", athleticsSnippet: "Bearkats football is an FCS powerhouse, driving immense local pride and massive tailgating events.", safetySnippet: "Huntsville is a quiet, rural town deeply protective of the university community." },
  { name: "Oakland University", studentLifeSnippet: "Oakland features a beautiful, affluent suburban campus that balances a massive commuter population with growing residential life.", athleticsSnippet: "Without a football team, Golden Grizzlies basketball dominates the sports culture.", safetySnippet: "Rochester Hills is an affluent, highly secure, and very peaceful suburb of Detroit." },
  { name: "Indiana Institute of Technology", studentLifeSnippet: "Indiana Tech is a small, highly focused, and career-driven campus heavily centered around engineering, business, and computer science.", athleticsSnippet: "The athletic culture is highly participatory, with a massive percentage of the student body involved in NAIA sports.", safetySnippet: "Fort Wayne is an affordable, generally safe Midwestern city." },
  { name: "Missouri State University-Springfield", studentLifeSnippet: "Missouri State offers a friendly, down-to-earth Midwestern campus experience with strong roots in education and business.", athleticsSnippet: "Bears basketball and baseball enjoy solid local support from the highly spirited student body.", safetySnippet: "Springfield is a bustling, very safe college town." },
  { name: "Arkansas State University", studentLifeSnippet: "A-State features a tight-knit, rural, and highly traditional Southern campus culture deeply focused on agriculture and local industry.", athleticsSnippet: "Red Wolves football is the primary social event of the fall, unifying the campus and surrounding region.", safetySnippet: "Jonesboro is a quiet, friendly, and exceptionally safe town." },
  { name: "University of Louisiana at Lafayette", studentLifeSnippet: "UL Lafayette is world-renowned for its incredible Cajun food culture, deeply vibrant social scene, and intense regional pride.", athleticsSnippet: "Ragin' Cajuns football and baseball are massive cultural juggernauts that shut down the town for tailgating.", safetySnippet: "Lafayette is a bustling, safe, and deeply welcoming Southern cultural hub." },
  { name: "Texas State University", studentLifeSnippet: "Texas State is famous for its gorgeous, hilly campus along the San Marcos River and a deeply laid-back, highly social student body.", athleticsSnippet: "Bobcats sports are growing, but floating the river and enjoying the local outdoors dominate the culture.", safetySnippet: "San Marcos is a classic, highly secure, and incredibly fun college town." },
  { name: "Quinsigamond Community College", studentLifeSnippet: "QCC provides an incredibly vital, diverse, and commuter-heavy environment focused entirely on career transitions and technical skills.", athleticsSnippet: "Athletics are very low-profile, as students are primarily focused on local jobs and transferring to 4-year schools.", safetySnippet: "The Worcester campus is heavily patrolled and highly focused on student safety." },
  { name: "Bloomfield College of Montclair State University", studentLifeSnippet: "This small, highly diverse liberal arts campus offers a tight-knit, supportive environment heavily focused on first-generation students.", athleticsSnippet: "Division II sports offer a strong sense of community, but academics and local careers take precedence.", safetySnippet: "Bloomfield is a quiet, generally safe suburban town." },
  { name: "Kennesaw State University", studentLifeSnippet: "KSU is a rapidly exploding, massive university offering a modern, heavily commuter-friendly campus near Atlanta.", athleticsSnippet: "Owls football has grown incredibly fast, fostering a massive and relatively new tailgating culture.", safetySnippet: "Kennesaw is a bustling, highly affluent, and very secure suburb." },
  { name: "University of Arkansas at Little Rock", studentLifeSnippet: "UA Little Rock is a diverse, heavily urban-integrated commuter campus focused on adult education, business, and health sciences.", athleticsSnippet: "Trojans basketball is the primary athletic draw in an otherwise academics-first culture.", safetySnippet: "The campus requires standard urban awareness but maintains a strong police presence." },
  { name: "University of Northern Colorado", studentLifeSnippet: "UNC offers a quiet, highly focused, and deeply collaborative environment famous for its elite education and theater programs.", athleticsSnippet: "Bears sports in the Big Sky conference draw decent local support, but the culture is very laid-back.", safetySnippet: "Greeley is an affordable, generally safe agricultural city." },
  { name: "Southern University and A & M College", studentLifeSnippet: "As the flagship of the Southern University System, this historic HBCU boasts incredible traditions, massive pride, and the legendary 'Human Jukebox' marching band.", athleticsSnippet: "Jaguars football and the massive 'Bayou Classic' rivalry game in New Orleans define the vibrant sports culture.", safetySnippet: "Baton Rouge requires urban awareness, but the campus is deeply protective of its tight-knit community." },
  { name: "University of West Florida", studentLifeSnippet: "UWF features a stunning, nature-immersed campus near the Gulf Coast, offering a laid-back, outdoorsy, and highly collaborative vibe.", athleticsSnippet: "Argonauts football recently exploded in popularity after winning a Division II national championship.", safetySnippet: "Pensacola is a friendly, secure coastal city with a very safe campus." },
  { name: "Grand Valley State University", studentLifeSnippet: "GVSU is a rapidly growing, modern campus blending strong residential life with a massive commuter population in West Michigan.", athleticsSnippet: "Lakers football is a Division II powerhouse, drawing huge student crowds to their immaculate facilities.", safetySnippet: "Allendale is a quiet, rural, and incredibly safe college town." },
  { name: "California State University-Fresno", studentLifeSnippet: "Fresno State is deeply tied to the massive agricultural industry of the Central Valley, boasting a gritty, hardworking, and diverse student body.", athleticsSnippet: "Bulldogs football is the absolute pride of the entire region, with the 'Red Wave' dominating game days.", safetySnippet: "Fresno requires typical urban street smarts, though the campus itself is heavily secured." },
  { name: "Tarleton State University", studentLifeSnippet: "Tarleton offers one of the most deeply traditional, fiercely loyal, and rural Texas college experiences in the state.", athleticsSnippet: "Texans football and rodeo are absolutely massive cultural events, deeply uniting the student body.", safetySnippet: "Stephenville is a tiny, incredibly safe, and deeply supportive cowboy town." },
  { name: "Western Kentucky University", studentLifeSnippet: "WKU features a famously beautiful hilltop campus and a highly spirited, friendly, and down-to-earth student body.", athleticsSnippet: "Hilltoppers basketball and football, along with the iconic 'Big Red' mascot, drive immense local pride.", safetySnippet: "Bowling Green is a classic, safe, and welcoming college town." },
  { name: "The University of Texas at El Paso", studentLifeSnippet: "UTEP is a highly unique, stunningly beautiful campus featuring Bhutanese architecture, deeply integrated into the US-Mexico border culture.", athleticsSnippet: "Miners basketball, playing in the historic Don Haskins Center, is the beating heart of El Paso sports.", safetySnippet: "El Paso is consistently ranked as one of the safest large cities in the United States." },
  { name: "University of Nebraska at Omaha", studentLifeSnippet: "UNO is a gritty, heavily commuter-focused urban campus that utilizes the growing city of Omaha as an extension of the classroom.", athleticsSnippet: "Mavericks ice hockey is the absolute pride of the university, playing in the massive Baxter Arena.", safetySnippet: "The campus is deeply integrated into Omaha and is generally very safe." },
  { name: "Marshall University", studentLifeSnippet: "Marshall boasts an incredibly tight-knit, fiercely loyal, and deeply historic campus culture in the Appalachian foothills.", athleticsSnippet: "Thundering Herd football is a cultural monolith, deeply tying the university and the town together through tragedy and triumph.", safetySnippet: "Huntington is a tough, historic town where the campus serves as a highly secure enclave." },
  { name: "Northern Arizona University", studentLifeSnippet: "NAU offers a deeply outdoorsy, progressive, and relaxed campus culture nestled in the high-altitude pine forests of Flagstaff.", athleticsSnippet: "Lumberjacks cross-country and distance running are national powerhouses, reflecting the campus's athletic identity.", safetySnippet: "Flagstaff is an incredibly beautiful, friendly, and safe mountain town." },
  { name: "University of South Dakota", studentLifeSnippet: "USD provides a highly intimate, rural, and traditional college experience with a strong focus on law, medicine, and business.", athleticsSnippet: "Coyotes football in the DakotaDome is the premier winter social event, drawing massive regional support.", safetySnippet: "Vermillion is a tiny, peaceful, and exceptionally safe Midwestern town." },
  { name: "Idaho State University", studentLifeSnippet: "ISU is a rugged, deeply outdoorsy campus serving as the state's leader in health professions and technical education.", athleticsSnippet: "Bengals football played inside the massive indoor Holt Arena is a unique and beloved campus tradition.", safetySnippet: "Pocatello is a quiet, affordable, and incredibly safe mountain town." },
  { name: "Lamar University", studentLifeSnippet: "Lamar offers a heavily industrial, gritty, and diverse campus deeply tied to the petrochemical engineering industries of Southeast Texas.", athleticsSnippet: "Cardinals sports enjoy solid local support, though the culture is heavily focused on academics and local jobs.", safetySnippet: "Beaumont requires standard urban awareness, but the campus maintains strong police patrols." },
  { name: "California State University-San Bernardino", studentLifeSnippet: "CSUSB is a highly diverse, heavily commuter-focused campus nestled against the beautiful San Bernardino Mountains.", athleticsSnippet: "Coyotes athletics are relatively low-profile, as students focus heavily on careers and local community building.", safetySnippet: "The campus area is generally safe, though students exercise standard caution in the broader city." },
  { name: "Indiana University-Indianapolis", studentLifeSnippet: "This massive urban campus blends intense health sciences and business programs directly into the bustling downtown of Indianapolis.", athleticsSnippet: "Athletics are minor, with students far more focused on clinicals, internships, and downtown nightlife.", safetySnippet: "The downtown campus is heavily secured, though standard city street smarts apply." },
  { name: "The University of Texas Rio Grande Valley", studentLifeSnippet: "UTRGV is a rapidly growing, incredibly diverse, and deeply vibrant institution serving as the cultural and academic hub of South Texas.", athleticsSnippet: "Vaqueros athletics are steadily growing a passionate local fanbase, deeply uniting the border region.", safetySnippet: "The campus is highly secure, safe, and heavily community-focused." },
  { name: "Southern University at New Orleans", studentLifeSnippet: "SUNO is a historic HBCU offering a deeply supportive, intimate, and highly resilient campus culture in the heart of New Orleans.", athleticsSnippet: "Athletics are highly community-driven, though students heavily participate in the broader New Orleans cultural scene.", safetySnippet: "The campus is well-secured, though students must navigate standard New Orleans urban environments." },
  { name: "Florida Gulf Coast University", studentLifeSnippet: "FGCU offers a stunning, heavily environmentally-conscious campus where students literally take classes next to a massive sandy beach.", athleticsSnippet: "Eagles basketball, forever famous for 'Dunk City,' is the absolute pride of the university's sports culture.", safetySnippet: "Fort Myers is a wealthy, incredibly safe, and highly secure coastal city." },
  { name: "Morehead State University", studentLifeSnippet: "Morehead State provides a deeply rural, highly affordable, and intimate educational experience nestled in the Appalachian foothills.", athleticsSnippet: "Eagles basketball and an incredibly dominant competitive cheerleading program are massive sources of pride.", safetySnippet: "Morehead is a tiny, peaceful, and exceptionally safe college town." },
  { name: "Arkansas Tech University", studentLifeSnippet: "ATU offers a quiet, highly traditional, and heavily engineering-focused rural campus experience in the Arkansas River Valley.", athleticsSnippet: "Wonder Boys and Golden Suns athletics are deeply beloved community events drawing strong local crowds.", safetySnippet: "Russellville is a safe, friendly, and deeply supportive town." },
  { name: "The University of Tennessee-Chattanooga", studentLifeSnippet: "UTC blends a gorgeous urban campus with a deeply outdoorsy, active student body that takes full advantage of the surrounding mountains and rivers.", athleticsSnippet: "Mocs sports are very popular, though weekend rock climbing and kayaking often dominate student life.", safetySnippet: "Chattanooga is a revitalized, highly secure, and very safe outdoor hub." },
  { name: "University of Wisconsin-Oshkosh", studentLifeSnippet: "UW Oshkosh provides a classic, hardworking Midwestern campus experience deeply tied to local industry and nursing.", athleticsSnippet: "Titans Division III sports are highly competitive and draw incredible support from the tight-knit student body.", safetySnippet: "Oshkosh is a friendly, quiet, and very safe college town." },
  { name: "University of Central Arkansas", studentLifeSnippet: "UCA offers a stunning, deeply traditional campus with a highly spirited student body and strong roots in education and the arts.", athleticsSnippet: "Bears football on 'The Stripes' (a uniquely striped turf field) is a massive cultural tradition.", safetySnippet: "Conway is famously known as the 'City of Colleges' and is incredibly safe." },
  { name: "South Carolina State University", studentLifeSnippet: "SC State is a deeply historic HBCU characterized by immense pride, a tight-knit family atmosphere, and the legendary 'Marching 101' band.", athleticsSnippet: "Bulldogs football is a massive cultural event, serving as a powerful unifier for students and alumni.", safetySnippet: "Orangeburg is a historic, generally safe town with a heavily community-focused campus." },
  { name: "Alabama State University", studentLifeSnippet: "ASU is a vibrant, deeply historic HBCU offering an energetic campus culture centered around extreme pride, music, and civil rights history.", athleticsSnippet: "Hornets football and the world-renowned 'Mighty Marching Hornets' band dominate the fall social scene.", safetySnippet: "The Montgomery campus is well-patrolled, though typical city awareness is required off-campus." },
  { name: "North Carolina A & T State University", studentLifeSnippet: "As the largest HBCU in the nation, NC A&T boasts an incredibly vibrant, STEM-focused, and deeply spirited 'Aggie Pride' culture.", athleticsSnippet: "Aggies football and the legendary 'GHOE' (Greatest Homecoming on Earth) are absolute cultural monoliths.", safetySnippet: "Greensboro is a bustling city where the campus is highly secure and deeply respected." },
  { name: "Jackson State University", studentLifeSnippet: "JSU offers a deeply historic, energetic HBCU experience defined by massive school pride, strong leadership programs, and the 'Sonic Boom of the South' marching band.", athleticsSnippet: "Tigers football, recently revitalized, is the absolute heartbeat of the campus and the city of Jackson.", safetySnippet: "Jackson requires high urban street smarts, but the campus serves as a strong, protective enclave." },
  { name: "Tennessee State University", studentLifeSnippet: "TSU provides a deeply urban, energetic HBCU experience with massive roots in agriculture, engineering, and the rich musical history of Nashville.", athleticsSnippet: "Tigers football and the incredible 'Aristocrat of Bands' dictate the vibrant athletic and social culture.", safetySnippet: "The campus is a secure urban oasis, though standard Nashville city precautions apply." },
  { name: "Grambling State University", studentLifeSnippet: "Grambling offers an intensely proud, deeply historic, and tight-knit HBCU experience in rural Louisiana.", athleticsSnippet: "Tigers football and the world-famous 'World Famed Tiger Marching Band' are iconic, historically elite cultural institutions.", safetySnippet: "Grambling is a tiny, rural, and exceptionally safe college town." },
  { name: "Texas Southern University", studentLifeSnippet: "TSU is an energetic, heavily diverse, and deeply historic HBCU completely integrated into the fast-paced urban environment of Houston.", athleticsSnippet: "Tigers sports, especially the 'Ocean of Soul' marching band, are massive sources of pride and entertainment.", safetySnippet: "The Third Ward requires typical urban awareness, but the university maintains a strong security presence." },
  { name: "Florida Agricultural and Mechanical University", studentLifeSnippet: "FAMU is a world-renowned HBCU offering a stunning campus set on the 'Highest of Seven Hills,' famous for immense pride and strong STEM programs.", athleticsSnippet: "Rattlers football and the legendary 'Marching 100' band are massive, iconic cultural forces that define the university.", safetySnippet: "Tallahassee is a busy college town, and the FAMU campus is deeply protective of its tight-knit community." }
];

async function main() {
  let count = 0;
  for (const college of data) {
    try {
      const result = await prisma.college.updateMany({
        where: { name: college.name },
        data: {
          studentLifeSnippet: college.studentLifeSnippet,
          athleticsSnippet: college.athleticsSnippet,
          safetySnippet: college.safetySnippet
        }
      });
      if (result.count > 0) count++;
      console.log(`Updated ${college.name}`);
    } catch (e) {
      console.error(`Failed to update ${college.name}`, e);
    }
  }
  console.log(`Successfully batch updated ${count} colleges.`);
}

main().finally(() => prisma.$disconnect());
