import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const data = [
  { name: "Clarkson University", studentLifeSnippet: "Clarkson is an intensely focused, tight-knit STEM institution where rigorous engineering projects and snowy winters build strong student camaraderie.", athleticsSnippet: "Division I men's and women's ice hockey absolutely dominate the sports culture, drawing fierce student support.", safetySnippet: "Potsdam is a remote, extremely safe college town in upstate New York where students feel highly secure." },
  { name: "Denver Seminary", studentLifeSnippet: "Denver Seminary offers a quiet, deeply spiritual, and highly focused academic environment catering almost entirely to graduate theology students.", athleticsSnippet: "There is no formal athletics program; students focus on outdoor recreation in the nearby Rocky Mountains.", safetySnippet: "Located in the quiet, affluent suburb of Littleton, the campus is exceptionally safe and peaceful." },
  { name: "University of Massachusetts-Lowell", studentLifeSnippet: "UMass Lowell features a gritty, rapidly growing, and heavily commuter-based campus deeply rooted in engineering and local industry.", athleticsSnippet: "River Hawks Division I ice hockey is the premier athletic event, rallying massive crowds to the Tsongas Center.", safetySnippet: "Lowell is an urban industrial city requiring typical street smarts, though the campus is heavily patrolled." },
  { name: "University of Central Florida", studentLifeSnippet: "UCF boasts a colossal, sun-drenched, and modern campus with an incredibly vibrant, diverse, and heavily Greek-influenced social scene.", athleticsSnippet: "Knights football is an absolute cultural force, with massive, spirited tailgates and 'Bounce House' game days.", safetySnippet: "The massive Orlando campus operates essentially as its own safe mini-city with extensive police presence." },
  { name: "University of New Hampshire-Franklin Pierce School of Law", studentLifeSnippet: "This specialized law school fosters an intense, professional, and intimate community focused almost entirely on intellectual property law.", athleticsSnippet: "Athletics are non-existent here, as students are entirely focused on legal studies and bar prep.", safetySnippet: "Concord, NH is a very quiet, safe capital city with minimal crime." },
  { name: "Michigan Technological University", studentLifeSnippet: "Michigan Tech is a secluded, heavily STEM-focused campus where students embrace the extreme cold and participate in massive winter carnivals.", athleticsSnippet: "Huskies ice hockey is the heart of the athletic scene, deeply uniting the isolated student body.", safetySnippet: "Houghton is a tiny, incredibly safe town in the Upper Peninsula where crime is almost unheard of." },
  { name: "DePaul University", studentLifeSnippet: "DePaul utilizes the entire city of Chicago as its campus, fostering a highly diverse, independent, and socially conscious student body.", athleticsSnippet: "Blue Demons basketball at Wintrust Arena is the main athletic draw, though many students prefer city nightlife.", safetySnippet: "The Lincoln Park campus is generally safe and upscale, though standard Chicago urban awareness is required." },
  { name: "Chapman University", studentLifeSnippet: "Chapman features a beautiful, affluent, and heavily arts-and-film-focused campus culture with strong Greek life in sunny Southern California.", athleticsSnippet: "Division III sports are low-profile, taking a back seat to the vibrant local arts and entertainment scene.", safetySnippet: "Orange is a quiet, highly secure, and picturesque suburban city." },
  { name: "University of Vermont", studentLifeSnippet: "UVM is legendary for its progressive, deeply outdoorsy, and environmentally conscious student body ('Groovy UV').", athleticsSnippet: "There is no football team; instead, Catamounts ice hockey and weekend ski trips completely dominate the winter culture.", safetySnippet: "Burlington is repeatedly ranked as one of the safest and best college towns in America." },
  { name: "University of Arkansas", studentLifeSnippet: "UARK offers a quintessential, massive Southern state school experience with a deeply loyal student body and dominant Greek life.", athleticsSnippet: "Calling the Hogs at Razorback football and baseball games is one of the most intense and unifying traditions in college sports.", safetySnippet: "Fayetteville is a highly spirited, safe college town deeply protective of its students." },
  { name: "Washington State University", studentLifeSnippet: "WSU is an isolated, spirited, and tightly-knit state school famous for its 'work hard, play hard' rural campus culture.", athleticsSnippet: "Cougars football in the Pac-12 drives the entire social calendar, with massive game-day tailgating.", safetySnippet: "Pullman is a small, remote college town considered exceptionally safe for students." },
  { name: "Thomas Jefferson University", studentLifeSnippet: "Jefferson is a deeply pre-professional, health-sciences-dominated university embedded in the urban fabric of Philadelphia.", athleticsSnippet: "Athletics are a very minor part of the experience, as students are heavily focused on clinicals and internships.", safetySnippet: "The Center City and East Falls campuses are well-secured, though standard Philly street smarts apply." },
  { name: "Creighton University", studentLifeSnippet: "Creighton fosters a highly rigorous, pre-med-heavy, and deeply community-oriented campus culture rooted in Jesuit traditions.", athleticsSnippet: "Bluejays basketball is a massive deal, serving as the premier social event for both the university and the city of Omaha.", safetySnippet: "Omaha is a generally safe Midwestern city, and the campus maintains a strong, secure perimeter." },
  { name: "Ohio Dominican University", studentLifeSnippet: "ODU offers a quiet, highly intimate, and faith-driven liberal arts education on a small campus in Columbus.", athleticsSnippet: "Division II sports are popular among the tight-knit student body, but the culture is more participatory than spectator-heavy.", safetySnippet: "The campus is a peaceful, secure enclave within the broader Columbus area." },
  { name: "The Catholic University of America", studentLifeSnippet: "CUA offers a stunning, enclosed campus with a deeply conservative, faith-driven, and highly politically active student body.", athleticsSnippet: "Division III athletics are low-profile, with students far more engaged in D.C. internships and campus ministry.", safetySnippet: "The Brookland neighborhood is generally safe, and the campus itself is heavily guarded and peaceful." },
  { name: "Loyola Marymount University", studentLifeSnippet: "LMU blends gorgeous bluff-top ocean views with a socially vibrant, affluent, and film/arts-focused Jesuit campus culture.", athleticsSnippet: "Lions basketball draws decent crowds, but beach trips and Hollywood internships dominate the extracurricular scene.", safetySnippet: "The Westchester/Playa Vista area is upscale, highly secure, and very safe." },
  { name: "Duquesne University", studentLifeSnippet: "Duquesne is a tight-knit, pre-professional Catholic university offering a quiet, enclosed campus vibe right next to downtown Pittsburgh.", athleticsSnippet: "Dukes basketball is the main athletic pride, though sports generally take a back seat to academics.", safetySnippet: "The bluff campus is heavily patrolled and considered an incredibly safe bubble within the city." },
  { name: "San Diego State University", studentLifeSnippet: "SDSU is famous for its vibrant, sun-soaked 'work hard, play hard' lifestyle, massive Greek system, and energetic student body.", athleticsSnippet: "Aztecs basketball is elite, drawing massive, rowdy student sections that dominate the winter social calendar.", safetySnippet: "The campus area is generally safe, with the university providing robust escort and transit services." },
  { name: "Rhode Island College", studentLifeSnippet: "RIC is a highly diverse, heavily commuter-based state college focused heavily on nursing, education, and local career advancement.", athleticsSnippet: "Division III athletics exist but play a minor role in the predominantly commuter lifestyle.", safetySnippet: "The suburban Mount Pleasant neighborhood of Providence is quiet and highly secure." },
  { name: "University of St Thomas", studentLifeSnippet: "St. Thomas offers a relatively affluent, pre-professional, and tightly-knit Catholic campus culture in the Twin Cities.", athleticsSnippet: "The Tommies recently made a historic leap to Division I, rapidly growing their athletic culture and school pride.", safetySnippet: "The St. Paul campus is nestled in a very safe, affluent, and quiet residential neighborhood." },
  { name: "Kansas State University", studentLifeSnippet: "K-State is beloved for its incredibly friendly, down-to-earth Midwestern culture and deep agricultural/engineering roots.", athleticsSnippet: "Wildcat football and 'Wabash Cannonball' traditions define the intensely loyal and spirited sports culture.", safetySnippet: "Manhattan ('The Little Apple') is a classic, deeply safe, and welcoming college town." },
  { name: "University of Louisville", studentLifeSnippet: "Louisville is an energetic, urban-integrated campus with a diverse, spirited student body and strong pre-professional programs.", athleticsSnippet: "Cardinals basketball and football are absolute cultural juggernauts that deeply connect the university to the city.", safetySnippet: "The campus requires typical urban awareness, but UofL operates a highly active campus police department." },
  { name: "Mississippi State University", studentLifeSnippet: "MSU offers a highly traditional, down-to-earth Southern college experience with a massive focus on agriculture, engineering, and Greek life.", athleticsSnippet: "SEC football is the centerpiece of campus life, marked by the iconic and deafening ringing of cowbells at Davis Wade Stadium.", safetySnippet: "Starkville is a rural, deeply supportive college town that is exceptionally safe." },
  { name: "Seton Hall University", studentLifeSnippet: "Seton Hall features a tight-knit, Catholic-driven community heavily focused on business, nursing, and close proximity to NYC.", athleticsSnippet: "Pirates basketball in the Big East is the massive, unifying pride of the university.", safetySnippet: "South Orange is an affluent, very safe suburban village with excellent campus security." },
  { name: "University of Houston", studentLifeSnippet: "UH is a massive, incredibly diverse, and rapidly rising research powerhouse deeply embedded in the bustling city of Houston.", athleticsSnippet: "Cougars basketball and football have seen massive recent success, heavily boosting campus spirit and tailgating culture.", safetySnippet: "The urban campus is heavily policed, but students are advised to be street-smart in surrounding neighborhoods." },
  { name: "Illinois Institute of Technology", studentLifeSnippet: "IIT is a deeply nerdy, highly rigorous, and heavily international STEM campus located just south of downtown Chicago.", athleticsSnippet: "Athletics are practically non-existent; students are fiercely focused on engineering projects and architecture.", safetySnippet: "The Bronzeville campus is well-secured, though students exercise standard urban caution off-campus." },
  { name: "Oklahoma State University-Main Campus", studentLifeSnippet: "OSU is famous for its 'America's Brightest Orange' pride, boasting a famously friendly, agriculture-rooted, and highly spirited Southern/Midwestern vibe.", athleticsSnippet: "Cowboys football and the massive 'America's Greatest Homecoming' celebration dictate the fall social scene.", safetySnippet: "Stillwater is a classic, safe, and heavily student-focused college town." },
  { name: "University of Alabama at Birmingham", studentLifeSnippet: "UAB is a massive, diverse, and heavily medical/research-focused urban campus that feels highly pre-professional.", athleticsSnippet: "Blazers football recently experienced a massive resurgence, reviving a strong sense of campus pride.", safetySnippet: "The downtown Birmingham campus is heavily patrolled and safe, though it requires typical city awareness." },
  { name: "Seattle University", studentLifeSnippet: "Seattle U offers a highly progressive, diverse, and socially conscious Jesuit education in the bustling Capitol Hill neighborhood.", athleticsSnippet: "Division I sports are low-profile; students are far more engaged in city life, arts, and activism.", safetySnippet: "The campus is a beautiful urban oasis, well-secured despite being in a busy part of Seattle." },
  { name: "Southern New Hampshire University", studentLifeSnippet: "While famous for its massive online presence, SNHU's physical campus offers a quiet, tight-knit, and heavily career-focused traditional college experience.", athleticsSnippet: "Division II Penmen sports have a solid local following among the small residential student body.", safetySnippet: "The Manchester campus is heavily wooded, secluded, and extremely safe." },
  { name: "University of Mississippi", studentLifeSnippet: "Ole Miss is the epitome of the classic Southern college experience, defined by intense tradition, massive Greek life, and beautiful grounds.", athleticsSnippet: "Tailgating in 'The Grove' before SEC football games is considered one of the most elite and formal sports traditions in America.", safetySnippet: "Oxford is a highly affluent, charming, and exceptionally safe college town." },
  { name: "University of North Carolina at Charlotte", studentLifeSnippet: "UNC Charlotte is a rapidly expanding, modern, and heavily commuter-friendly campus closely tied to the city's banking and tech industries.", athleticsSnippet: "The relatively new 49ers football program is steadily growing a dedicated tailgating and campus sports culture.", safetySnippet: "The sprawling suburban campus is considered very safe and well-patrolled." },
  { name: "Florida International University", studentLifeSnippet: "FIU is a colossal, incredibly diverse, and dynamic institution that serves as a major cultural and academic hub for Miami.", athleticsSnippet: "Panthers sports are growing in popularity, but the beach and Miami nightlife often take precedence.", safetySnippet: "The massive campus functions as its own secure city within the broader Miami area." },
  { name: "Biola University", studentLifeSnippet: "Biola offers a deeply conservative, highly intentional evangelical Christian environment where faith is integrated into every aspect of student life.", athleticsSnippet: "Athletics are minor, with students far more focused on campus ministry, music, and community service.", safetySnippet: "Located in suburban La Mirada, the enclosed campus is exceptionally peaceful and safe." },
  { name: "University of Nevada-Las Vegas", studentLifeSnippet: "UNLV features a highly diverse, heavily commuter-based student body deeply tied to the hospitality and entertainment industries of Vegas.", athleticsSnippet: "Runnin' Rebels basketball is the historic pride of the university, drawing passionate local crowds.", safetySnippet: "The campus is heavily secured, though the surrounding urban Vegas area requires street smarts." },
  { name: "George Fox University", studentLifeSnippet: "George Fox is a small, tight-knit Christian university with a strong Quaker heritage, focusing heavily on community and service.", athleticsSnippet: "Division III sports are highly participatory, fostering strong camaraderie rather than massive spectator events.", safetySnippet: "Newberg is a quiet, rural Oregon town that is exceptionally safe." },
  { name: "University of Wyoming", studentLifeSnippet: "UW is incredibly isolated and deeply outdoorsy, offering a rugged, down-to-earth culture with a massive focus on agriculture and engineering.", athleticsSnippet: "As the only 4-year university in the state, Cowboys football unites the entire state of Wyoming on game days.", safetySnippet: "Laramie is a small, tough, and extremely safe frontier college town." },
  { name: "Louisiana State University", studentLifeSnippet: "LSU is a colossal, spirited powerhouse defined by a massive Greek system, incredible Cajun food culture, and intense state pride.", athleticsSnippet: "Saturday nights in 'Death Valley' for SEC football are legendary, creating one of the most intimidating and loud sports atmospheres in the world.", safetySnippet: "Baton Rouge requires some urban awareness, but the massive campus is well-policed." },
  { name: "Texas Christian University", studentLifeSnippet: "TCU boasts a wealthy, preppy, and highly spirited campus culture with a massive Greek life presence and stunning facilities.", athleticsSnippet: "Horned Frogs football is an absolute juggernaut, completely dominating the fall social calendar in Fort Worth.", safetySnippet: "The campus and surrounding affluent neighborhoods are exceptionally safe and heavily secured." },
  { name: "University of North Carolina at Greensboro", studentLifeSnippet: "UNCG is a highly diverse, arts-and-education-focused campus known for a laid-back, progressive, and incredibly welcoming student body.", athleticsSnippet: "Without a football team, Spartans basketball is the main athletic draw, though arts and theater dominate the culture.", safetySnippet: "The campus is generally safe, blending nicely into the broader Greensboro community." },
  { name: "The University of Montana", studentLifeSnippet: "UM is a haven for outdoorsy, environmentally conscious students who spend their free time hiking, skiing, and fly-fishing.", athleticsSnippet: "Grizzlies football is a massive statewide event, with Washington-Grizzly Stadium serving as the loudest venue in the FCS.", safetySnippet: "Missoula is a deeply progressive, friendly, and highly safe mountain town." },
  { name: "New Mexico State University", studentLifeSnippet: "NMSU offers a laid-back, highly diverse, and agriculture-rooted culture in the beautiful, sun-drenched high desert.", athleticsSnippet: "Aggies basketball and the fierce 'Battle of I-25' rivalry with UNM define the campus sports culture.", safetySnippet: "Las Cruces is a quiet, spread-out city that is generally very safe for students." },
  { name: "University of North Dakota", studentLifeSnippet: "UND is an intensely focused, cold-weather campus world-renowned for its elite aerospace and aviation programs.", athleticsSnippet: "Fighting Hawks ice hockey is essentially a religion here, played in one of the most lavish arenas in college sports.", safetySnippet: "Grand Forks is a small, incredibly safe Midwestern town with very low crime rates." },
  { name: "University of Idaho", studentLifeSnippet: "U of I features a remarkably beautiful, hilly campus with a strong, traditional Greek system and a tight-knit rural community.", athleticsSnippet: "Vandals football played inside the unique 'Kibbie Dome' is the quirky, beloved center of campus sports.", safetySnippet: "Moscow is a quintessential, peaceful, and exceptionally safe Pacific Northwest college town." },
  { name: "South Dakota State University", studentLifeSnippet: "SDSU is a friendly, deeply agricultural, and engineering-focused campus with a massive, down-to-earth Midwestern student body.", athleticsSnippet: "Jackrabbits football and the massive 'Hobo Day' homecoming celebration are the biggest events of the year.", safetySnippet: "Brookings is widely considered one of the safest and most welcoming college towns in America." },
  { name: "Montana State University", studentLifeSnippet: "MSU is exploding in popularity, attracting deeply outdoorsy, ski-obsessed, and STEM-focused students to the Rocky Mountains.", athleticsSnippet: "Bobcat football and the intense 'Brawl of the Wild' rivalry dictate the massive sports culture.", safetySnippet: "Bozeman is an affluent, booming outdoor hub that remains incredibly safe." },
  { name: "Utah State University", studentLifeSnippet: "USU offers a massive, highly spirited, and predominantly LDS student body that embraces rugged outdoor recreation.", athleticsSnippet: "The 'Hurd' student section at Aggies basketball games is notoriously loud, organized, and deeply passionate.", safetySnippet: "Logan is a beautiful, isolated mountain town repeatedly ranked as one of the safest in the US." },
  { name: "Potomac State College of West Virginia University", studentLifeSnippet: "This small, rural junior college offers an incredibly intimate, deeply agricultural, and highly supportive transition to a 4-year degree.", athleticsSnippet: "Junior college athletics are highly participatory and community-focused rather than major spectator events.", safetySnippet: "Keyser is a tiny, rural Appalachian town where crime is practically non-existent." },
  { name: "Ball State University", studentLifeSnippet: "Ball State is a classic, mid-sized Midwestern campus with renowned telecommunications/broadcasting programs and a friendly vibe.", athleticsSnippet: "Cardinals football and basketball enjoy solid local support, though the culture is relatively laid-back.", safetySnippet: "Muncie is a typical, quiet college town that is generally very safe." },
  { name: "University of Maine", studentLifeSnippet: "UMaine offers a rugged, deeply forested campus where students embrace the extreme cold and focus heavily on marine and environmental sciences.", athleticsSnippet: "Black Bears ice hockey is the absolute pride of the university, drawing intense and rowdy student crowds.", safetySnippet: "Orono is a tiny, isolated college town that is incredibly safe." },
  { name: "University of North Alabama", studentLifeSnippet: "UNA is a beautiful, historic, and rapidly growing regional campus famous for keeping live lion mascots on campus.", athleticsSnippet: "Lions football recently transitioned to Division I FCS, generating massive excitement and new tailgating traditions.", safetySnippet: "Florence is a charming, safe Southern town with a strong music history." },
  { name: "Western Michigan University", studentLifeSnippet: "WMU is a large, highly spirited university famous for its elite aviation program and an outgoing, social student body.", athleticsSnippet: "Broncos hockey and football are the major athletic draws, fostering a strong sense of campus pride.", safetySnippet: "Kalamazoo is a bustling college town where the campus perimeter is well-patrolled." },
  { name: "Kent State University", studentLifeSnippet: "Kent State offers a massive, arts-and-fashion-forward campus with a diverse, highly active, and socially conscious student body.", athleticsSnippet: "Golden Flashes sports enjoy solid support, but the massive fashion and arts scene often takes center stage.", safetySnippet: "Kent is a classic, deeply historic college town that prioritizes student safety." },
  { name: "University of Memphis", studentLifeSnippet: "UofM is a gritty, heavily commuter-based, and highly diverse urban campus deeply connected to the city's rich music and logistics industries.", athleticsSnippet: "Memphis Tigers basketball is the absolute heartbeat of the city and the university, driving immense local pride.", safetySnippet: "The urban campus requires street smarts, but the university maintains a heavy security presence." },
  { name: "Eastern Virginia Medical School", studentLifeSnippet: "EVMS is an intensely focused, purely graduate-level medical and health professions school heavily integrated into local hospitals.", athleticsSnippet: "There is no athletics program; the entire culture is focused on grueling clinical rotations and medical research.", safetySnippet: "The Norfolk medical complex is heavily secured by campus and hospital police." },
  { name: "North Dakota State University", studentLifeSnippet: "NDSU is a deeply agricultural and engineering-driven powerhouse with a famously resilient, friendly, and fiercely loyal student body.", athleticsSnippet: "Bison football is an FCS dynasty, and game days at the Fargodome are massive, statewide spectacles.", safetySnippet: "Fargo is a large but incredibly safe Midwestern city with a very secure campus." },
  { name: "University of South Alabama", studentLifeSnippet: "South Alabama is a rapidly growing, diverse, and modern campus heavily focused on nursing and allied health professions.", athleticsSnippet: "Jaguars football recently built a brand-new on-campus stadium, massively boosting school spirit and tailgating.", safetySnippet: "The Mobile campus is spacious, well-lit, and very safe." },
  { name: "University of Southern Mississippi", studentLifeSnippet: "Southern Miss is known for its beautiful, arts-focused campus and a deeply friendly, tight-knit Southern community.", athleticsSnippet: "Golden Eagles football and baseball are massive draws, with the 'Eagle Walk' serving as a premier game-day tradition.", safetySnippet: "Hattiesburg is a classic, welcoming college town that is very secure." },
  { name: "East Carolina University", studentLifeSnippet: "ECU is famous for its massive, incredibly spirited, and outgoing student body that embraces a legendary 'work hard, play hard' lifestyle.", athleticsSnippet: "Pirates football is the absolute core of the university's identity, featuring one of the most intense and rowdy tailgating scenes in the state.", safetySnippet: "Greenville is a dedicated college town where the campus is heavily policed." },
  { name: "Wichita State University", studentLifeSnippet: "WSU is an innovative, heavily commuter-focused urban campus renowned for its elite aerospace engineering programs.", athleticsSnippet: "Without a football team, Shockers basketball is a massive cultural force, drawing loud and passionate crowds.", safetySnippet: "The campus is generally safe, though standard urban precautions are recommended in surrounding Wichita." }
];

async function main() {
  let count = 0;
  for (const college of data) {
    try {
      const result = await prisma.college.updateMany({
        where: { name: college.name },
        data: {
          studentLifeSnippet: college.studentLifeSnippet,
          athleticsSnippet: college.athleticsSnippet,
          safetySnippet: college.safetySnippet
        }
      });
      if (result.count > 0) count++;
      console.log(`Updated ${college.name}`);
    } catch (e) {
      console.error(`Failed to update ${college.name}`, e);
    }
  }
  console.log(`Successfully batch updated ${count} colleges.`);
}

main().finally(() => prisma.$disconnect());
